version: '2.0'
services:
  api:
    container_name: demo_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules

    # Sobrescrevendo as configs do .env
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: demo_api_db
    image: postgres:14
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
